### ISSUE TITLE
Some Fixes

### ISSUE THREAD

**Issue by HemanthJabalpuri** [iamsaalim/gsi2zip#2]
@danascape 
It seems like you have to add some more to this.
- No setup.sh
- Also you havent copied system.transfer.list, system.patch.dat to the output and zip folders
- Option -p system is obsolete since it is default one
- https://github.com/danascape/img2zip/blob/3d9898daee0261f6e7cadba97a5172f7814c9b77/strip.sh#L5
It needs **ls** I think and also **exit** in **if** block

Thanks

**Comment by danascape** [comment]
I am planning to rewrite the script, thanks for notifying and sorry for late replies. I'll fix it up soon.
